/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/status-check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description 認証状態取得API */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            redirectPath?: string;
          };
        };
      };
      responses: {
        /** @description 認証されている時のレスポンス */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @description 認証後のリダイレクト先 */
              callbackUrl?: string;
            };
          };
        };
        /** @description リクエストボディが存在しない時のレスポンス */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message?: string;
            };
          };
        };
        /** @description 認証されていない時のレスポンス */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message?: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
