openapi: 3.0.0

info:
  version: 1.0.0
  title: EnvHub API
  description: EnvHubのフロントエンド向けAPIです。

paths:
  /auth/status-check: 
    post:
      description: 認証状態取得API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                redirectPath:
                  type: string

      responses:
        '200':
          description: 認証されている時のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  callbackUrl:
                    description: 認証後のリダイレクト先
                    type: string

        "400":
          description: リクエストボディが存在しない時のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

        "401":
          description: 認証されていない時のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /uploads/confirm:
    post:
      description: envファイルアップロードAPI
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                upload_target_files:
                  type: string
                  format: binary
                meta_data:
                  type: object
                  properties:
                    repo_name:
                      type: string
                    repo_id:
                      type: number
                    commit_message:
                      type: string
                      
      responses:
        "200":
          description: アップロード成功時レスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

        "403":
          description: 認証情報不足時レスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

        "500":
          description: アップロード失敗時レスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string