openapi: 3.0.0

info:
  version: 1.0.0
  title: EnvHub API
  description: EnvHubのフロントエンド向けAPIです。

components:
  schemas:
    UnAuthorizedErrorObject:
      type: object
      properties:
        message:
          type: string

    ServerSideErrorObject:
      type: object
      properties:
        message:
         type: string

  responses:
    UnauthorizedError:
      description: 認証情報不足時のレスポンス
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UnAuthorizedErrorObject"

paths:
  /auth/status-check: 
    post:
      description: 認証状態取得API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                redirectPath:
                  type: string

      responses:
        '200':
          description: 認証されている時のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  callbackUrl:
                    description: 認証後のリダイレクト先
                    type: string

        "400":
          description: リクエストボディが存在しない時のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

        "401":
          description: 認証されていない時のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /uploads/confirm:
    post:
      description: envファイルアップロードAPI
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                upload_target_files:
                  type: string
                  format: binary
                meta_data:
                  type: object
                  properties:
                    repo_name:
                      type: string
                    repo_id:
                      type: number
                    commit_message:
                      type: string
                      
      responses:
        "200":
          description: アップロード成功時レスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

        "403":
          description: 認証情報不足時レスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

        "500":
          description: アップロード失敗時レスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /repositories/{repositoryId}/commits:
    get:
      description: リポジトリに紐づくコミット一覧取得API
      parameters:
        - name: repositoryId
          in: path
          required: true
          schema:
            type: number
            description: リポジトリID

      responses:
        "200":
          description: 取得成功時レスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    commit_uuid:
                      type: string
                    commit_message:
                      type: string
                    commiter_name:
                      type: string
                      nullable: true
                    created_at:
                      type: string

        "403":
          description: 認証情報不足時レスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

        "500":
          description: 取得失敗時レスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /repositories/{repositoryId}/commits/{commitUuid}/files:
    get:
      description: コミットIDに紐づくファイル一覧取得API
      parameters:
        - name: repositoryId
          in: path
          required: true
          schema:
            type: number
            description: リポジトリID
        - name: commitUuid
          in: path
          required: true
          schema:
            type: string
            description: コミットUUID

      responses:
        "200":
          description: 取得成功時レスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    created_at:
                      type: string
                    metadata:
                      type: object
                      properties:
                        size:
                          type: number

        "403":
         $ref: "#/components/responses/UnauthorizedError"
          
        "500":
          description: 取得失敗時レスポンス
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/ServerSideErrorObject"