// This file is auto-generated by @hey-api/openapi-ts

export const UnAuthorizedErrorObjectSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        }
    }
} as const;

export const ServerSideErrorObjectSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        }
    }
} as const;