// This file is auto-generated by @hey-api/openapi-ts

export type ServerSideErrorObject = {
    message?: string;
};

export type UnAuthorizedErrorObject = {
    message?: string;
};

export type PostAuthStatusCheckData = {
    body: {
        redirectPath?: string;
    };
};

export type PostAuthStatusCheckResponse = ({
    /**
     * 認証後のリダイレクト先
     */
    callbackUrl?: string;
});

export type PostAuthStatusCheckError = ({
    message?: string;
});

export type PostUploadsConfirmData = {
    body: {
        upload_target_files?: (Blob | File);
        meta_data?: {
            repo_name?: string;
            repo_id?: number;
            commit_message?: string;
        };
    };
};

export type PostUploadsConfirmResponse = ({
    message?: string;
});

export type PostUploadsConfirmError = ({
    message?: string;
});

export type GetRepositoriesByRepositoryIdCommitsData = {
    path: {
        repositoryId: number;
    };
};

export type GetRepositoriesByRepositoryIdCommitsResponse = (Array<{
    commit_uuid?: string;
    commit_message?: string;
    commiter_name?: (string) | null;
    created_at?: string;
}>);

export type GetRepositoriesByRepositoryIdCommitsError = ({
    message?: string;
});

export type GetRepositoriesByRepositoryIdCommitsByCommitUuidFilesData = {
    path: {
        commitUuid: string;
        repositoryId: number;
    };
};

export type GetRepositoriesByRepositoryIdCommitsByCommitUuidFilesResponse = (Array<{
    name?: string;
    created_at?: string;
    metadata?: {
        size?: number;
    };
}>);

export type GetRepositoriesByRepositoryIdCommitsByCommitUuidFilesError = (UnAuthorizedErrorObject | ServerSideErrorObject);

export type GetRepositoriesByRepositoryIdCommitsByCommitUuidFilesDownloadData = {
    path: {
        commitUuid: string;
        repositoryId: number;
    };
};

export type GetRepositoriesByRepositoryIdCommitsByCommitUuidFilesDownloadResponse = (Array<{
    signedUrl?: string;
    error?: (string) | null;
    path?: (string) | null;
}>);

export type GetRepositoriesByRepositoryIdCommitsByCommitUuidFilesDownloadError = (UnAuthorizedErrorObject | ServerSideErrorObject);

export type GetRepositoriesByRepositoryIdCommitsByCommitUuidFilesDownloadByFileNameData = {
    path: {
        commitUuid: string;
        fileName: string;
        repositoryId: number;
    };
};

export type GetRepositoriesByRepositoryIdCommitsByCommitUuidFilesDownloadByFileNameResponse = ({
    signedUrl?: string;
});

export type GetRepositoriesByRepositoryIdCommitsByCommitUuidFilesDownloadByFileNameError = (UnAuthorizedErrorObject | ServerSideErrorObject);