name: OpenAPIをredocとしてgithub pagesにデプロイする

on:
  push:
    branches:
      - main
    paths:
      - "openapi/*" # OpenAPIのyamlだけをCI対象にする
  workflow_dispatch: # 手動実行用

jobs:
  build-redoc:
    runs-on: ubuntu-latest
    steps:
      # リポジトリを取得する
      - uses: actions/checkout@v4

      - name: redocを生成する
        run: npx @redocly/cli build-docs ./openapi/openapi.yaml -o ./docs/envhub-api-docs.html

      - name: artifactsとして生成したredocを保存する
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
  deploy-redoc:
    needs: build-redoc
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: GitHub pagesにデプロイする
        id: deployment
        uses: actions/deploy-pages@v4